//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leilao.Data
{
	using Leilao.Entidades;
	using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LEILAOEntities : DbContext
    {
        public LEILAOEntities()
            : base("name=LEILAOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LANCES> LANCES { get; set; }
        public virtual DbSet<PESSOA> PESSOA { get; set; }
        public virtual DbSet<PRODUTO> PRODUTO { get; set; }
    }
}
