//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leilao.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANCES
    {
        public int ID { get; set; }
        public int ID_PRODUTO { get; set; }
        public int ID_PESSOA { get; set; }
        public decimal LANCE { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
